### PR TITLE
Created initial interfaces and data modeling for the server's Redis monitors. 

### PR DESCRIPTION
**Pull request by wesleyjia34**
Two files added:

interfaces.ts
* Interfaces for objects to be implemented as part of the RedisMonitors (see Miro wireframes).
* Enforces properties, methods, and corresponding types for all related objects etc.

data-stores.ts
* Currently added the constructor functions for the EventLog, implemented as a LinkedList

Also updated the tsconfig.json to remove the sourceMap property, which is not really needed for node server-side development (it's a Chrome developer tool)

### CODE REVIEW

**Comment by wesleyjia34** [comment]
I just added more commits. Comments:

There is now a working Redis monitoring interface! 
* redis-monitors.ts exports an object that can be used by the server to both interface with the Redis clients/connections and also read keyspace event logs
* redis-monitors.ts also initializes the subscribers for keyspace notifications, for every keyspace

I also corrected some of the data modeling for the Redis monitors.

To-do:
* redis-monitors.ts can be better modularized / refactored - the code has some nested callback hell going on.
* Tests need to be written for the monitors before proceeding further

**Review by swattoboe — APPROVED** [review]
Makes sense to not have sourcemaps for node.

**Review by swattoboe — APPROVED** [review]
Everything looks good, interface declarations make sense, comments are helpful.  Add function for the doubly LL also looks good.

**Review by swattoboe — APPROVED** [review]
redis-monitors.ts and server.ts look great, so far

**Pull request merged**
